# Generated by Django 3.2.15 on 2024-03-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0173_create_default_category_and_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products'),
        ),
    ]
