# Generated by Django 3.2.15 on 2024-03-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(max_length=500, upload_to='thumbnails'),
        ),
    ]
